version: 0.2

env:
  shell: bash

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget 
https://releases.hashicorp.com/terraform/1.2.1/terraform_1.2.1_linux_amd64.zip"
      - "unzip terraform_1.2.1_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - rm -rf .terraform
      - terraform init

  build:
    commands:
      - terraform plan -no-color

  post_build:
    commands:
      - echo "terraform plan stage"